// 
// Decompiled by Procyon v0.5.36
// 

package com.ibm.dmh.scan.classify.reservedWords;

import java.util.TreeMap;
import java.util.Map;

public class ReservedWordsEASY
{
    private static final String copyright = "Licensed Material - Property of IBM\n5724-V27\nCopyright IBM Corp. 1996, 2014\nThe source code for this program is not published or otherwise\ndivested of its trade secrets, irrespective of what has been\ndeposited with the U.S. Copyright Office.";
    protected static final Map<String, String> reservedWords;
    
    public static boolean containsKey(final String token) {
        return ReservedWordsEASY.reservedWords.containsKey(token);
    }
    
    public static String get(final String token) {
        return ReservedWordsEASY.reservedWords.get(token);
    }
    
    static {
        (reservedWords = new TreeMap<String, String>()).put("ACCESS", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("AFTER-BREAK", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("AFTER-LINE", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("AFTER-SCREEN", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("AND", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("ATTR", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("BEFORE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("BEFORE-BREAK", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("BEFORE-LINE", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("BEFORE-SCREEN", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("BREAK-LEVEL", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("BUSHU", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("BY", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("CALL", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("CASE", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("CHECKPOINT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("CHKP", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("CHKP-STATUS", "ReservedWord,  3,  0");
        ReservedWordsEASY.reservedWords.put("CLEAR", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("CLOSE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("COL", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("COLOR", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("COMMIT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("CONTROL", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("COPY", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("CURSOR", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("D", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("DECLARE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("DEFAULT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("DEFINE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("DELETE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("DENWA", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("DISPLAY", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("DLI", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("DO", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("DRAW", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("DUPLICATE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("E", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("ELEMENT-RECORD", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("ELSE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("ELSE-IF", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("END", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("END-CASE", "ScopeDelimit,  3,  0");
        ReservedWordsEASY.reservedWords.put("END-DO", "ScopeDelimit,  3,  0");
        ReservedWordsEASY.reservedWords.put("END-IF", "ScopeDelimit,  3,  0");
        ReservedWordsEASY.reservedWords.put("END-PROC", "ScopeDelimit,  3,  0");
        ReservedWordsEASY.reservedWords.put("ENDPAGE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("END-REPEAT", "ScopeDelimit,  3,  0");
        ReservedWordsEASY.reservedWords.put("ENDTABLE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("ENTER", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("EOF", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("EQ", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("ERROR", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("EXECUTE", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("EXIT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("EXTERNAL", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F1", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F2", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F3", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F4", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F5", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F6", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F7", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F8", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F9", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F10", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F11", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F12", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F13", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F14", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F15", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F16", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F17", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F18", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F19", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F20", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F21", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F22", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F23", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("F24", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("FETCH", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("FILE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("FILE-STATUS", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("FILL", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("FINAL", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("FIRST", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("FIRST-DUP", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("FOR", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("GE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("GET", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("GO", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("GOTO", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("GQ", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("GR", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("GRAPH", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("GT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("HEADING", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("HEX", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("HIGH-VALUES", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("IDD", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("IDMS", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("IF", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("IN", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("INITIATION", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("INSERT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("JOB", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("JUSTIFY", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("KANJI-DATE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("KANJI-TIME", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("KANJI-DATE-LONG", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("KEY", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("KEY-PRESSED", "ReservedWord,  3,  0");
        ReservedWordsEASY.reservedWords.put("KOKUGO", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("KUN", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LAST-DUP", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LEVEL", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LIKE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("LINE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LINE-COUNT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LINE-NUMBER", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LINK", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("LIST", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("LOGICAL-RECORD", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("LOW-VALUES", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LQ", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LS", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("LT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("MACRO", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("MASK", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("MATCHED", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("MEND", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("MESSAGE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("MOVE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("MSTART", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("NE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("NEWPAGE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("NOMASK", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("NOPRINT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("NOT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("NOTE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("NOTITLE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("NOVERIFY", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("NQ", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("NULL", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("OF", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("OR", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("OTHERWISE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PA1", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PA2", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PA3", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PAGE-COUNT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PAGE-NUMBER", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PARM", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("PARM-REGISTER", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PATH-ID", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PATTERN", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PERFORM", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("POINT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("POP", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("POS", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PRIMARY", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PRINT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("PROC", "Verb,          3,  0");
        ReservedWordsEASY.reservedWords.put("PROCEDURE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("PROGRAM", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("PUSH", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("PUT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("READ", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("RECORD", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("RECORD-COUNT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("RECORD-LENGTH", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("REFRESH", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("RELEASE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("RENUM", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("REPEAT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("REPORT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("REPORT-INPUT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("RESHOW", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("RESTART", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("RETRIEVE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("RETURN-CODE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("ROLLBACK", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("ROW", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("S", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SCREEN", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SEARCH", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SECONDARY", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SELECT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SEQUENCE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SET", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SIZE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SKIP", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SOKAKU", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SORT", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SQL", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("STOP", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SUM", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("SYSDATE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SYSDATE-LONG", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SYSIN", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SYSIPT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SYSLST", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SYSPRINT", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SYSSNAP", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SYSTIME", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("SYSUSERID", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("TALLY", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("TERM-COLUMNS", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("TERM-NAME", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("TERM-ROWS", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("TERMINATION", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("TITLE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("TO", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("TRANSFER", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("TRC", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("UNIQUE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("UNTIL", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("UPDATE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("UPPERCASE", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("VALUE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("VERIFY", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("W", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("WHEN", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("WORK", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("WRITE", "Verb,          2,  0");
        ReservedWordsEASY.reservedWords.put("X", "ReservedWord,  2,  0");
        ReservedWordsEASY.reservedWords.put("XRST", "ReservedWord,  2,  0");
    }
}
