// 
// Decompiled by Procyon v0.5.36
// 

package com.ibm.dmh.scan.classify.reservedWords;

import java.util.TreeMap;
import java.util.Map;

public class ReservedWordsASM_optableYOP
{
    private static final String copyright = "Licensed Material - Property of IBM\n5724-V27\nCopyright IBM Corp. 2017\nThe source code for this program is not published or otherwise\ndivested of its trade secrets, irrespective of what has been\ndeposited with the U.S. Copyright Office.";
    private static final Map<String, String> opcodes;
    
    public static boolean containsKey(final String token) {
        return ReservedWordsASM_optableYOP.opcodes.containsKey(token);
    }
    
    public static String get(final String key) {
        return ReservedWordsASM_optableYOP.opcodes.get(key);
    }
    
    static {
        (opcodes = new TreeMap<String, String>()).put("A", "RX   5A   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ACONTROL", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("ACTR", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AD", "RX   6A   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ADATA", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("ADB", "RXE  ED1A R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ADBR", "RRE  B31A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ADR", "RR   2A   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AE", "RX   7A   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AEB", "RXE  ED0A R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AEBR", "RRE  B30A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AEJECT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AER", "RR   3A   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AG", "RXY  E308 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AGF", "RXY  E318 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AGFR", "RRE  B918 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AGHI", "RI   A7.B R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("AGO", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AGOB", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AGR", "RRE  B908 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AH", "RX   4A   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AHI", "RI   A7.A R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("AHY", "RXY  E37A R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AIF", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AIFB", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AINSERT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AL", "RX   5E   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ALC", "RXY  E398 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ALCG", "RXY  E388 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ALCGR", "RRE  B988 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ALCR", "RRE  B998 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ALG", "RXY  E30A R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ALGF", "RXY  E31A R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ALGFR", "RRE  B91A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ALGR", "RRE  B90A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ALIAS", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("ALR", "RR   1E   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ALY", "RXY  E35E R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AMODE", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("ANOP", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AP", "SS   FA   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AR", "RR   1A   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AREAD", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("ASPACE", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("AU", "RX   7E   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AUR", "RR   3E   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AW", "RX   6E   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("AWR", "RR   2E   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AXBR", "RRE  B34A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AXR", "RR   36   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("AY", "RXY  E35A R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("B", "RX   47F. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BAKR", "RRE  B240 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BAL", "RX   45   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BALR", "RR   05   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BAS", "RX   4D   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BASR", "RR   0D   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BASSM", "RR   0C   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BC", "RX   47   M1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BCR", "RR   07   M1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BCT", "RX   46   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BCTG", "RXY  E346 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BCTGR", "RRE  B946 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BCTR", "RR   06   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BE", "RX   478. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BER", "RR   078. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BH", "RX   472. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BHR", "RR   072. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BL", "RX   474. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BLR", "RR   074. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BM", "RX   474. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BMR", "RR   074. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BNE", "RX   477. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BNER", "RR   077. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BNH", "RX   47D. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BNHR", "RR   07D. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BNL", "RX   47B. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BNLR", "RR   07B. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BNM", "RX   47B. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BNMR", "RR   07B. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BNO", "RX   47E. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BNOR", "RR   07E. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BNP", "RX   47D. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BNPR", "RR   07D. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BNZ", "RX   477. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BNZR", "RR   077. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BO", "RX   471. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BOR", "RR   071. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BP", "RX   472. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BPR", "RR   072. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BR", "RR   07F. R2");
        ReservedWordsASM_optableYOP.opcodes.put("BRAS", "RI   A7.5 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRASL", "RIL  C0.5 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRC", "RI   A7.4 M1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRCL", "RIL  C0.4 M1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRCT", "RI   A7.6 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRCTG", "RI   A7.7 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRE", "RI   A784 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BREL", "RIL  C084 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRH", "RI   A724 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRHL", "RIL  C024 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRL", "RI   A744 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRLL", "RIL  C044 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRM", "RI   A744 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRML", "RIL  C044 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNE", "RI   A774 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNEL", "RIL  C074 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNH", "RI   A7D4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNHL", "RIL  C0D4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNL", "RI   A7B4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNLL", "RIL  C0B4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNM", "RI   A7B4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNML", "RIL  C0B4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNO", "RI   A7E4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNOL", "RIL  C0E4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNP", "RI   A7D4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNPL", "RIL  C0D4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNZ", "RI   A774 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRNZL", "RIL  C074 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRO", "RI   A714 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BROL", "RIL  C014 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRP", "RI   A724 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRPL", "RIL  C024 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRU", "RI   A7F4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRUL", "RIL  C0F4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRXH", "RSI  84   R1,R3,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRXHG", "RIE  EC44 R1,R3,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRXLE", "RSI  85   R1,R3,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRXLG", "RIE  EC45 R1,R3,I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRZ", "RI   A784 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BRZL", "RIL  C084 I2");
        ReservedWordsASM_optableYOP.opcodes.put("BSA", "RRE  B25A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BSG", "RRE  B258 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BSM", "RR   0B   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("BXH", "RS   86   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BXHG", "RSY  EB44 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BXLE", "RS   87   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BXLEG", "RSY  EB45 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BZ", "RX   478. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("BZR", "RR   078. R2");
        ReservedWordsASM_optableYOP.opcodes.put("C", "RX   59   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CATTR", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("CCW", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("CCW0", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("CCW1", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("CD", "RX   69   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CDB", "RXE  ED19 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CDBR", "RRE  B319 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CDFBR", "RRE  B395 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CDFR", "RRE  B3B5 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CDGBR", "RRE  B3A5 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CDGR", "RRE  B3C5 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CDR", "RR   29   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CDS", "RS   BB   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CDSG", "RSY  EB3E R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CDSY", "RSY  EB31 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CE", "RX   79   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CEB", "RXE  ED09 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CEBR", "RRE  B309 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CEFBR", "RRE  B394 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CEFR", "RRE  B3B4 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CEGBR", "RRE  B3A4 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CEGR", "RRE  B3C4 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CEJECT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("CER", "RR   39   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CFC", "S    B21A D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CFDBR", "RRF  B399 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CFDR", "RRF  B3B9 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CFEBR", "RRF  B398 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CFER", "RRF  B3B8 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CFXBR", "RRF  B39A R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CFXR", "RRF  B3BA R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CG", "RXY  E320 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CGDBR", "RRF  B3A9 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CGDR", "RRF  B3C9 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CGEBR", "RRF  B3A8 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CGER", "RRF  B3C8 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CGF", "RXY  E330 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CGFR", "RRE  B930 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CGHI", "RI   A7.F R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("CGR", "RRE  B920 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CGXBR", "RRF  B3AA R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CGXR", "RRF  B3CA R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CH", "RX   49   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CHI", "RI   A7.E R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("CHY", "RXY  E379 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CKSM", "RRE  B241 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CL", "RX   55   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLC", "SS   D5   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLCL", "RR   0F   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CLCLE", "RS   A9   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLCLU", "RSY  EB8F R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLG", "RXY  E321 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLGF", "RXY  E331 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLGFR", "RRE  B931 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CLGR", "RRE  B921 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CLI", "SI   95   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("CLIY", "SIY  EB55 D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("CLM", "RS   BD   R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLMH", "RSY  EB20 R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLMY", "RSY  EB21 R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CLR", "RR   15   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CLST", "RRE  B25D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CLY", "RXY  E355 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CMPSC", "RRE  B263 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CNOP", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("COM", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("COPY", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("CP", "SS   F9   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CPYA", "RRE  B24D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CR", "RR   19   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CS", "RS   BA   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CSCH", "S    B230");
        ReservedWordsASM_optableYOP.opcodes.put("CSECT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("CSG", "RSY  EB30 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CSP", "RRE  B250 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CSPG", "RRE  B98A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CSY", "RSY  EB14 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CU12", "RRE  B2A7 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CU14", "RRE  B9B0 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CU21", "RRE  B2A6 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CU24", "RRE  B9B1 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CU41", "RRE  B9B2 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CU42", "RRE  B9B3 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CUSE", "RRE  B257 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CUTFU", "RRE  B2A7 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CUUTF", "RRE  B2A6 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CVB", "RX   4F   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CVBG", "RXY  E30E R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CVBY", "RXY  E306 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CVD", "RX   4E   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CVDG", "RXY  E32E R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CVDY", "RXY  E326 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("CXBR", "RRE  B349 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CXD", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("CXFBR", "RRE  B396 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CXFR", "RRE  B3B6 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CXGBR", "RRE  B3A6 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CXGR", "RRE  B3C6 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CXR", "RRE  B369 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("CY", "RXY  E359 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("D", "RX   5D   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DC", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("DD", "RX   6D   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DDB", "RXE  ED1D R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DDBR", "RRE  B31D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DDR", "RR   2D   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DE", "RX   7D   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DEB", "RXE  ED0D R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DEBR", "RRE  B30D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DER", "RR   3D   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DIDBR", "RRF  B35B R1,R3,R2,M4");
        ReservedWordsASM_optableYOP.opcodes.put("DIEBR", "RRF  B353 R1,R3,R2,M4");
        ReservedWordsASM_optableYOP.opcodes.put("DL", "RXY  E397 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DLG", "RXY  E387 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DLGR", "RRE  B987 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DLR", "RRE  B997 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DP", "SS   FD   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DR", "RR   1D   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DROP", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("DS", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("DSECT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("DSG", "RXY  E30D R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DSGF", "RXY  E31D R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("DSGFR", "RRE  B91D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DSGR", "RRE  B90D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DXBR", "RRE  B34D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("DXD", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("DXR", "RRE  B22D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("EAR", "RRE  B24F R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ED", "SS   DE   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("EDMK", "SS   DF   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("EFPC", "RRE  B38C R1");
        ReservedWordsASM_optableYOP.opcodes.put("EJECT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("END", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("ENTRY", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("EPAIR", "RRE  B99A R1");
        ReservedWordsASM_optableYOP.opcodes.put("EPAR", "RRE  B226 R1");
        ReservedWordsASM_optableYOP.opcodes.put("EPSW", "RRE  B98D R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("EQU", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("EREG", "RRE  B249 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("EREGG", "RRE  B90E R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ESAIR", "RRE  B99B R1");
        ReservedWordsASM_optableYOP.opcodes.put("ESAR", "RRE  B227 R1");
        ReservedWordsASM_optableYOP.opcodes.put("ESEA", "RRE  B99D R1");
        ReservedWordsASM_optableYOP.opcodes.put("ESTA", "RRE  B24A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("EX", "RX   44   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("EXITCTL", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("EXTRN", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("FIDBR", "RRF  B35F R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("FIDR", "RRE  B37F R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("FIEBR", "RRF  B357 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("FIER", "RRE  B377 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("FIXBR", "RRF  B347 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("FIXR", "RRE  B367 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("GBLA", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("GBLB", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("GBLC", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("HDR", "RR   24   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("HER", "RR   34   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("HSCH", "S    B231");
        ReservedWordsASM_optableYOP.opcodes.put("IAC", "RRE  B224 R1");
        ReservedWordsASM_optableYOP.opcodes.put("IC", "RX   43   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ICM", "RS   BF   R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ICMH", "RSY  EB80 R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ICMY", "RSY  EB81 R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ICTL", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("ICY", "RXY  E373 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("IDTE", "RRF  B98E R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("IIHH", "RI   A5.0 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("IIHL", "RI   A5.1 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("IILH", "RI   A5.2 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("IILL", "RI   A5.3 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("IPK", "S    B20B");
        ReservedWordsASM_optableYOP.opcodes.put("IPM", "RRE  B222 R1");
        ReservedWordsASM_optableYOP.opcodes.put("IPTE", "RRE  B221 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ISEQ", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("ISKE", "RRE  B229 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("IVSK", "RRE  B223 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("J", "RI   A7F4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JAS", "RI   A7.5 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JASL", "RIL  C0.5 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JC", "RI   A7.4 M1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JCT", "RI   A7.6 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JCTG", "RI   A7.7 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JE", "RI   A784 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JH", "RI   A724 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JL", "RI   A744 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLC", "RIL  C0.4 M1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLE", "RIL  C084 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLH", "RIL  C024 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLL", "RIL  C044 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLM", "RIL  C044 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLNE", "RIL  C074 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLNH", "RIL  C0D4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLNL", "RIL  C0B4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLNM", "RIL  C0B4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLNO", "RIL  C0E4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLNOP", "RIL  C004 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLNP", "RIL  C0D4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLNZ", "RIL  C074 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLO", "RIL  C014 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLP", "RIL  C024 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLU", "RIL  C0F4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JLZ", "RIL  C084 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JM", "RI   A744 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JNE", "RI   A774 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JNH", "RI   A7D4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JNL", "RI   A7B4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JNM", "RI   A7B4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JNO", "RI   A7E4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JNOP", "RI   A704 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JNP", "RI   A7D4 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JNZ", "RI   A774 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JO", "RI   A714 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JP", "RI   A724 I2");
        ReservedWordsASM_optableYOP.opcodes.put("JXH", "RSI  84   R1,R3,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JXHG", "RIE  EC44 R1,R3,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JXLE", "RSI  85   R1,R3,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JXLEG", "RIE  EC45 R1,R3,I2");
        ReservedWordsASM_optableYOP.opcodes.put("JZ", "RI   A784 I2");
        ReservedWordsASM_optableYOP.opcodes.put("KDB", "RXE  ED18 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("KDBR", "RRE  B318 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("KEB", "RXE  ED08 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("KEBR", "RRE  B308 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("KIMD", "RRE  B93E R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("KLMD", "RRE  B93F R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("KM", "RRE  B92E R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("KMAC", "RRE  B91E R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("KMC", "RRE  B92F R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("KXBR", "RRE  B348 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("L", "RX   58   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LA", "RX   41   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LAE", "RX   51   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LAM", "RS   9A   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LAMY", "RSY  EB9A R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LARL", "RIL  C0.0 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("LASP", "SSE  E500 D1(B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LAY", "RXY  E371 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LB", "RXY  E376 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LCDBR", "RRE  B313 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LCDR", "RR   23   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LCEBR", "RRE  B303 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LCER", "RR   33   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LCGFR", "RRE  B913 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LCGR", "RRE  B903 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LCLA", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("LCLB", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("LCLC", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("LCR", "RR   13   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LCTL", "RS   B7   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LCTLG", "RSY  EB2F R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LCXBR", "RRE  B343 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LCXR", "RRE  B363 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LD", "RX   68   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LDE", "RXE  ED24 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LDEB", "RXE  ED04 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LDEBR", "RRE  B304 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LDER", "RRE  B324 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LDR", "RR   28   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LDXBR", "RRE  B345 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LDXR", "RR   25   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LDY", "RXY  ED65 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LE", "RX   78   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LEDBR", "RRE  B344 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LEDR", "RR   35   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LER", "RR   38   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LEXBR", "RRE  B346 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LEXR", "RRE  B366 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LEY", "RXY  ED64 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LFPC", "S    B29D D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LG", "RXY  E304 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LGB", "RXY  E377 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LGF", "RXY  E314 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LGFR", "RRE  B914 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LGH", "RXY  E315 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LGHI", "RI   A7.9 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("LGR", "RRE  B904 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LH", "RX   48   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LHI", "RI   A7.8 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("LHY", "RXY  E378 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LLGC", "RXY  E390 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LLGF", "RXY  E316 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LLGFR", "RRE  B916 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LLGH", "RXY  E391 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LLGT", "RXY  E317 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LLGTR", "RRE  B917 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LLIHH", "RI   A5.C R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("LLIHL", "RI   A5.D R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("LLILH", "RI   A5.E R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("LLILL", "RI   A5.F R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("LM", "RS   98   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LMD", "SS   EF   R1,R3,D2(B2),D4(B4)");
        ReservedWordsASM_optableYOP.opcodes.put("LMG", "RSY  EB04 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LMH", "RSY  EB96 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LMY", "RSY  EB98 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LNDBR", "RRE  B311 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LNDR", "RR   21   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LNEBR", "RRE  B301 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LNER", "RR   31   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LNGFR", "RRE  B911 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LNGR", "RRE  B901 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LNR", "RR   11   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LNXBR", "RRE  B341 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LNXR", "RRE  B361 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LOCTR", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("LPDBR", "RRE  B310 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LPDR", "RR   20   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LPEBR", "RRE  B300 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LPER", "RR   30   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LPGFR", "RRE  B910 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LPGR", "RRE  B900 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LPQ", "RXY  E38F R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LPR", "RR   10   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LPSW", "S    8200 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LPSWE", "S    B2B2 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LPXBR", "RRE  B340 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LPXR", "RRE  B360 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LR", "RR   18   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LRA", "RX   B1   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LRAG", "RXY  E303 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LRAY", "RXY  E313 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LRDR", "RR   25   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LRER", "RR   35   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LRV", "RXY  E31E R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LRVG", "RXY  E30F R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LRVGR", "RRE  B90F R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LRVH", "RXY  E31F R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LRVR", "RRE  B91F R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTDBR", "RRE  B312 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTDR", "RR   22   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTEBR", "RRE  B302 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTER", "RR   32   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTGFR", "RRE  B912 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTGR", "RRE  B902 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTORG", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("LTR", "RR   12   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTXBR", "RRE  B342 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LTXR", "RRE  B362 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LURA", "RRE  B24B R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LURAG", "RRE  B905 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LXD", "RXE  ED25 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LXDB", "RXE  ED05 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LXDBR", "RRE  B305 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LXDR", "RRE  B325 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LXE", "RXE  ED26 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LXEB", "RXE  ED06 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LXEBR", "RRE  B306 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LXER", "RRE  B326 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LXR", "RRE  B365 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("LY", "RXY  E358 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("LZDR", "RRE  B375 R1");
        ReservedWordsASM_optableYOP.opcodes.put("LZER", "RRE  B374 R1");
        ReservedWordsASM_optableYOP.opcodes.put("LZXR", "RRE  B376 R1");
        ReservedWordsASM_optableYOP.opcodes.put("M", "RX   5C   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MACRO", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("MAD", "RXF  ED3E R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MADB", "RXF  ED1E R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MADBR", "RRF  B31E R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MADR", "RRF  B33E R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MAE", "RXF  ED2E R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MAEB", "RXF  ED0E R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MAEBR", "RRF  B30E R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MAER", "RRF  B32E R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MC", "SI   AF   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("MD", "RX   6C   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MDB", "RXE  ED1C R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MDBR", "RRE  B31C R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MDE", "RX   7C   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MDEB", "RXE  ED0C R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MDEBR", "RRE  B30C R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MDER", "RR   3C   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MDR", "RR   2C   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ME", "RX   7C   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MEE", "RXE  ED37 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MEEB", "RXE  ED17 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MEEBR", "RRE  B317 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MEER", "RRE  B337 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MEND", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("MER", "RR   3C   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MEXIT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("MGHI", "RI   A7.D R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("MH", "RX   4C   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MHELP", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("MHI", "RI   A7.C R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("ML", "RXY  E396 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MLG", "RXY  E386 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MLGR", "RRE  B986 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MLR", "RRE  B996 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MNOTE", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("MP", "SS   FC   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MR", "RR   1C   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MS", "RX   71   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MSCH", "S    B232 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MSD", "RXF  ED3F R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MSDB", "RXF  ED1F R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MSDBR", "RRF  B31F R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MSDR", "RRF  B33F R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MSE", "RXF  ED2F R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MSEB", "RXF  ED0F R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MSEBR", "RRF  B30F R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MSER", "RRF  B32F R1,R3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MSG", "RXY  E30C R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MSGF", "RXY  E31C R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MSGFR", "RRE  B91C R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MSGR", "RRE  B90C R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MSR", "RRE  B252 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MSTA", "RRE  B247 R1");
        ReservedWordsASM_optableYOP.opcodes.put("MSY", "RXY  E351 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVC", "SS   D2   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVCDK", "SSE  E50F D1(B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVCIN", "SS   E8   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVCK", "SS   D9   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optableYOP.opcodes.put("MVCL", "RR   0E   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MVCLE", "RS   A8   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVCLU", "RSY  EB8E R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVCP", "SS   DA   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optableYOP.opcodes.put("MVCS", "SS   DB   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optableYOP.opcodes.put("MVCSK", "SSE  E50E D1(B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVI", "SI   92   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("MVIY", "SIY  EB52 D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("MVN", "SS   D1   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVO", "SS   F1   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MVPG", "RRE  B254 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MVST", "RRE  B255 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MVZ", "SS   D3   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MXBR", "RRE  B34C R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MXD", "RX   67   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MXDB", "RXE  ED07 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("MXDBR", "RRE  B307 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MXDR", "RR   27   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("MXR", "RR   26   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("N", "RX   54   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("NC", "SS   D4   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("NG", "RXY  E380 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("NGR", "RRE  B980 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("NI", "SI   94   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("NIHH", "RI   A5.4 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("NIHL", "RI   A5.5 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("NILH", "RI   A5.6 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("NILL", "RI   A5.7 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("NIY", "SIY  EB54 D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("NOP", "RX   470. D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("NOPR", "RR   070. R2");
        ReservedWordsASM_optableYOP.opcodes.put("NR", "RR   14   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("NY", "RXY  E354 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("O", "RX   56   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("OC", "SS   D6   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("OG", "RXY  E381 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("OGR", "RRE  B981 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("OI", "SI   96   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("OIHH", "RI   A5.8 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("OIHL", "RI   A5.9 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("OILH", "RI   A5.A R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("OILL", "RI   A5.B R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("OIY", "SIY  EB56 D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("OPSYN", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("OR", "RR   16   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("ORG", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("OY", "RXY  E356 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("PACK", "SS   F2   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("PALB", "RRE  B248");
        ReservedWordsASM_optableYOP.opcodes.put("PC", "S    B218 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("PKA", "SS   E9   D1(B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("PKU", "SS   E1   D1(B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("PLO", "SS   EE   R1,D2(B2),R3,D4(B4)");
        ReservedWordsASM_optableYOP.opcodes.put("POP", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("PR", "E    0101");
        ReservedWordsASM_optableYOP.opcodes.put("PRINT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("PT", "RRE  B228 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("PTI", "RRE  B99E R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("PTLB", "S    B20D");
        ReservedWordsASM_optableYOP.opcodes.put("PUNCH", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("PUSH", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("RCHP", "S    B23B");
        ReservedWordsASM_optableYOP.opcodes.put("REPRO", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("RLL", "RSY  EB1D R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("RLLG", "RSY  EB1C R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("RMODE", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("RP", "S    B277 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("RRBE", "RRE  B22A R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("RSCH", "S    B238");
        ReservedWordsASM_optableYOP.opcodes.put("RSECT", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("S", "RX   5B   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SAC", "S    B219 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SACF", "S    B279 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SAL", "S    B237");
        ReservedWordsASM_optableYOP.opcodes.put("SAM24", "E    010C");
        ReservedWordsASM_optableYOP.opcodes.put("SAM31", "E    010D");
        ReservedWordsASM_optableYOP.opcodes.put("SAM64", "E    010E");
        ReservedWordsASM_optableYOP.opcodes.put("SAR", "RRE  B24E R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SCHM", "S    B23C");
        ReservedWordsASM_optableYOP.opcodes.put("SCK", "S    B204 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SCKC", "S    B206 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SCKPF", "E    0107");
        ReservedWordsASM_optableYOP.opcodes.put("SD", "RX   6B   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SDB", "RXE  ED1B R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SDBR", "RRE  B31B R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SDR", "RR   2B   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SE", "RX   7B   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SEB", "RXE  ED0B R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SEBR", "RRE  B30B R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SER", "RR   3B   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SETA", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("SETAF", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("SETB", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("SETC", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("SETCF", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("SFPC", "RRE  B384 R1");
        ReservedWordsASM_optableYOP.opcodes.put("SG", "RXY  E309 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SGF", "RXY  E319 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SGFR", "RRE  B919 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SGR", "RRE  B909 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SH", "RX   4B   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SHY", "RXY  E37B R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SIE", "S    B214 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SIGP", "RS   AE   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SL", "RX   5F   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLA", "RS   8B   R1,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLAG", "RSY  EB0B R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLB", "RXY  E399 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLBG", "RXY  E389 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLBGR", "RRE  B989 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SLBR", "RRE  B999 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SLDA", "RS   8F   R1,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLDL", "RS   8D   R1,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLG", "RXY  E30B R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLGF", "RXY  E31B R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLGFR", "RRE  B91B R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SLGR", "RRE  B90B R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SLL", "RS   89   R1,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLLG", "RSY  EB0D R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SLR", "RR   1F   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SLY", "RXY  E35F R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SP", "SS   FB   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SPACE", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("SPKA", "S    B20A D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SPM", "RR   04   R1");
        ReservedWordsASM_optableYOP.opcodes.put("SPT", "S    B208 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SPX", "S    B210 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SQD", "RXE  ED35 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SQDB", "RXE  ED15 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SQDBR", "RRE  B315 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SQDR", "RRE  B244 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SQE", "RXE  ED34 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SQEB", "RXE  ED14 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SQEBR", "RRE  B314 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SQER", "RRE  B245 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SQXBR", "RRE  B316 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SQXR", "RRE  B336 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SR", "RR   1B   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SRA", "RS   8A   R1,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SRAG", "RSY  EB0A R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SRDA", "RS   8E   R1,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SRDL", "RS   8C   R1,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SRL", "RS   88   R1,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SRLG", "RSY  EB0C R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SRNM", "S    B299 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SRP", "SS   F0   D1(L1,B1),D2(B2),I3");
        ReservedWordsASM_optableYOP.opcodes.put("SRST", "RRE  B25E R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SRSTU", "RRE  B9BE R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SSAIR", "RRE  B99F R1");
        ReservedWordsASM_optableYOP.opcodes.put("SSAR", "RRE  B225 R1");
        ReservedWordsASM_optableYOP.opcodes.put("SSCH", "S    B233 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SSKE", "RRE  B22B R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SSM", "S    8000 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ST", "RX   50   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STAM", "RS   9B   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STAMY", "RSY  EB9B R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STAP", "S    B212 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("START", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("STC", "RX   42   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCK", "S    B205 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCKC", "S    B207 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCKE", "S    B278 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCM", "RS   BE   R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCMH", "RSY  EB2C R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCMY", "RSY  EB2D R1,M3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCPS", "S    B23A D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCRW", "S    B239 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCTG", "RSY  EB25 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCTL", "RS   B6   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STCY", "RXY  E372 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STD", "RX   60   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STDY", "RXY  ED67 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STE", "RX   70   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STEY", "RXY  ED66 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STFL", "S    B2B1 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STFPC", "S    B29C D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STG", "RXY  E324 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STH", "RX   40   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STHY", "RXY  E370 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STIDP", "S    B202 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STM", "RS   90   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STMG", "RSY  EB24 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STMH", "RSY  EB26 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STMY", "RSY  EB90 R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STNSM", "SI   AC   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("STOSM", "SI   AD   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("STPQ", "RXY  E38E R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STPT", "S    B209 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STPX", "S    B211 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STRAG", "SSE  E502 D1(B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STRV", "RXY  E33E R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STRVG", "RXY  E32F R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STRVH", "RXY  E33F R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STSCH", "S    B234 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STSI", "S    B27D D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("STURA", "RRE  B246 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("STURG", "RRE  B925 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("STY", "RXY  E350 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SU", "RX   7F   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SUR", "RR   3F   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SVC", "RR   0A   I1");
        ReservedWordsASM_optableYOP.opcodes.put("SW", "RX   6F   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("SWR", "RR   2F   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SXBR", "RRE  B34B R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SXR", "RR   37   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("SY", "RXY  E35B R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TAM", "E    010B");
        ReservedWordsASM_optableYOP.opcodes.put("TAR", "RRE  B24C R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TB", "RRE  B22C R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TBDR", "RRF  B351 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TBEDR", "RRF  B350 R1,M3,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TCDB", "RXE  ED11 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TCEB", "RXE  ED10 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TCXB", "RXE  ED12 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("THDER", "RRE  B358 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("THDR", "RRE  B359 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TITLE", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("TM", "SI   91   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("TMH", "RI   A7.0 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("TMHH", "RI   A7.2 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("TMHL", "RI   A7.3 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("TML", "RI   A7.1 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("TMLH", "RI   A7.0 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("TMLL", "RI   A7.1 R1,I2");
        ReservedWordsASM_optableYOP.opcodes.put("TMY", "SIY  EB51 D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("TP", "RSL  EBC0 D1(L1,B1)");
        ReservedWordsASM_optableYOP.opcodes.put("TPI", "S    B236 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TPROT", "SSE  E501 D1(B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TR", "SS   DC   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TRACE", "RS   99   R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TRACG", "RSY  EB0F R1,R3,D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TRAP2", "E    01FF");
        ReservedWordsASM_optableYOP.opcodes.put("TRAP4", "S    B2FF D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TRE", "RRE  B2A5 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TROO", "RRE  B993 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TROT", "RRE  B992 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TRT", "SS   DD   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TRTO", "RRE  B991 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TRTR", "SS   D0   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TRTT", "RRE  B990 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("TS", "S    9300 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("TSCH", "S    B235 D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("UNPK", "SS   F3   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("UNPKA", "SS   EA   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("UNPKU", "SS   E2   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("UPT", "E    0102");
        ReservedWordsASM_optableYOP.opcodes.put("USING", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("WXTRN", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("X", "RX   57   R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("XATTR", "HLASM");
        ReservedWordsASM_optableYOP.opcodes.put("XC", "SS   D7   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableYOP.opcodes.put("XG", "RXY  E382 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("XGR", "RRE  B982 R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("XI", "SI   97   D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("XIY", "SIY  EB57 D1(B1),I2");
        ReservedWordsASM_optableYOP.opcodes.put("XR", "RR   17   R1,R2");
        ReservedWordsASM_optableYOP.opcodes.put("XSCH", "S    B276");
        ReservedWordsASM_optableYOP.opcodes.put("XY", "RXY  E357 R1,D2(X2,B2)");
        ReservedWordsASM_optableYOP.opcodes.put("ZAP", "SS   F8   D1(L1,B1),D2(L2,B2)");
    }
}
