// 
// Decompiled by Procyon v0.5.36
// 

package com.ibm.dmh.scan.classify.reservedWords;

import java.util.TreeMap;
import java.util.Map;

public class ReservedWordsASM_optableDOS
{
    private static final String copyright = "Licensed Material - Property of IBM\n5724-V27\nCopyright IBM Corp. 2017\nThe source code for this program is not published or otherwise\ndivested of its trade secrets, irrespective of what has been\ndeposited with the U.S. Copyright Office.";
    private static final Map<String, String> opcodes;
    
    public static boolean containsKey(final String token) {
        return ReservedWordsASM_optableDOS.opcodes.containsKey(token);
    }
    
    public static String get(final String key) {
        return ReservedWordsASM_optableDOS.opcodes.get(key);
    }
    
    static {
        (opcodes = new TreeMap<String, String>()).put("A", "RX   5A   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("ACTR", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("AD", "RX   6A   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("ADR", "RR   2A   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("AE", "RX   7A   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("AER", "RR   3A   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("AGO", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("AGOB", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("AH", "RX   4A   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("AIF", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("AIFB", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("AL", "RX   5E   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("ALR", "RR   1E   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("ANOP", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("AP", "SS   FA   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("AR", "RR   1A   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("AU", "RX   7E   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("AUR", "RR   3E   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("AW", "RX   6E   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("AWR", "RR   2E   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("AXR", "RR   36   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("B", "RX   47F. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BAL", "RX   45   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BALR", "RR   05   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("BC", "RX   47   M1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BCR", "RR   07   M1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("BCT", "RX   46   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BCTR", "RR   06   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("BE", "RX   478. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BER", "RR   078. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BH", "RX   472. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BHR", "RR   072. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BL", "RX   474. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BLR", "RR   074. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BM", "RX   474. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BMR", "RR   074. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BNE", "RX   477. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BNER", "RR   077. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BNH", "RX   47D. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BNHR", "RR   07D. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BNL", "RX   47B. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BNLR", "RR   07B. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BNM", "RX   47B. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BNMR", "RR   07B. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BNO", "RX   47E. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BNOR", "RR   07E. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BNP", "RX   47D. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BNPR", "RR   07D. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BNZ", "RX   477. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BNZR", "RR   077. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BO", "RX   471. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BOR", "RR   071. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BP", "RX   472. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BPR", "RR   072. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BR", "RR   07F. R2");
        ReservedWordsASM_optableDOS.opcodes.put("BXH", "RS   86   R1,R3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BXLE", "RS   87   R1,R3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BZ", "RX   478. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("BZR", "RR   078. R2");
        ReservedWordsASM_optableDOS.opcodes.put("C", "RX   59   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CCW", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("CD", "RX   69   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CDR", "RR   29   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("CDS", "RS   BB   R1,R3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CE", "RX   79   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CER", "RR   39   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("CH", "RX   49   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CL", "RX   55   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CLC", "SS   D5   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CLCL", "RR   0F   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("CLI", "SI   95   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("CLM", "RS   BD   R1,M3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CLR", "RR   15   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("CLRIO", "S    9D01 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CNOP", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("COM", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("COPY", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("CP", "SS   F9   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CR", "RR   19   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("CS", "RS   BA   R1,R3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CSECT", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("CVB", "RX   4F   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("CVD", "RX   4E   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("D", "RX   5D   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("DC", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("DD", "RX   6D   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("DDR", "RR   2D   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("DE", "RX   7D   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("DER", "RR   3D   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("DP", "SS   FD   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("DR", "RR   1D   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("DROP", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("DS", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("DSECT", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("ED", "SS   DE   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("EDMK", "SS   DF   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("EJECT", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("END", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("ENTRY", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("EQU", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("EX", "RX   44   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("EXTRN", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("GBLA", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("GBLB", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("GBLC", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("HDR", "RR   24   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("HDV", "S    9E01 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("HER", "RR   34   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("HIO", "S    9E00 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("IC", "RX   43   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("ICM", "RS   BF   R1,M3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("ICTL", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("IPK", "S    B20B");
        ReservedWordsASM_optableDOS.opcodes.put("ISEQ", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("ISK", "RR   09   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("L", "RX   58   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LA", "RX   41   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LCDR", "RR   23   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LCER", "RR   33   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LCLA", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("LCLB", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("LCLC", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("LCR", "RR   13   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LCTL", "RS   B7   R1,R3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LD", "RX   68   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LDR", "RR   28   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LE", "RX   78   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LER", "RR   38   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LH", "RX   48   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LM", "RS   98   R1,R3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LNDR", "RR   21   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LNER", "RR   31   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LNR", "RR   11   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LPDR", "RR   20   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LPER", "RR   30   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LPR", "RR   10   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LPSW", "S    8200 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LR", "RR   18   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LRA", "RX   B1   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("LRDR", "RR   25   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LRER", "RR   35   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LTDR", "RR   22   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LTER", "RR   32   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("LTORG", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("LTR", "RR   12   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("M", "RX   5C   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MACRO", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("MC", "SI   AF   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("MD", "RX   6C   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MDE", "RX   7C   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MDER", "RR   3C   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("MDR", "RR   2C   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("ME", "RX   7C   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MEND", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("MER", "RR   3C   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("MEXIT", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("MH", "RX   4C   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MNOTE", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("MP", "SS   FC   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MR", "RR   1C   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("MVC", "SS   D2   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MVCIN", "SS   E8   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MVCL", "RR   0E   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("MVI", "SI   92   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("MVN", "SS   D1   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MVO", "SS   F1   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MVZ", "SS   D3   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MXD", "RX   67   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("MXDR", "RR   27   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("MXR", "RR   26   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("N", "RX   54   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("NC", "SS   D4   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("NI", "SI   94   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("NOP", "RX   470. D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("NOPR", "RR   070. R2");
        ReservedWordsASM_optableDOS.opcodes.put("NR", "RR   14   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("O", "RX   56   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("OC", "SS   D6   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("OI", "SI   96   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("OR", "RR   16   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("ORG", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("PACK", "SS   F2   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("PRINT", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("PTLB", "S    B20D");
        ReservedWordsASM_optableDOS.opcodes.put("PUNCH", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("RDD", "SI   85   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("REPRO", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("RRB", "S    B213 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("S", "RX   5B   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SCK", "S    B204 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SCKC", "S    B206 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SD", "RX   6B   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SDR", "RR   2B   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("SE", "RX   7B   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SER", "RR   3B   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("SETA", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("SETB", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("SETC", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("SH", "RX   4B   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SIO", "S    9C00 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SIOF", "S    9C01 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SL", "RX   5F   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SLA", "RS   8B   R1,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SLDA", "RS   8F   R1,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SLDL", "RS   8D   R1,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SLL", "RS   89   R1,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SLR", "RR   1F   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("SP", "SS   FB   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SPACE", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("SPKA", "S    B20A D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SPM", "RR   04   R1");
        ReservedWordsASM_optableDOS.opcodes.put("SPT", "S    B208 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SR", "RR   1B   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("SRA", "RS   8A   R1,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SRDA", "RS   8E   R1,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SRDL", "RS   8C   R1,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SRL", "RS   88   R1,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SRP", "SS   F0   D1(L1,B1),D2(B2),I3");
        ReservedWordsASM_optableDOS.opcodes.put("SSK", "RR   08   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("SSM", "S    8000 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("ST", "RX   50   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("START", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("STC", "RX   42   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STCK", "S    B205 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STCKC", "S    B207 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STCM", "RS   BE   R1,M3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STCTL", "RS   B6   R1,R3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STD", "RX   60   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STE", "RX   70   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STH", "RX   40   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STIDC", "S    B203 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STIDP", "S    B202 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STM", "RS   90   R1,R3,D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("STNSM", "SI   AC   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("STOSM", "SI   AD   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("STPT", "S    B209 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SU", "RX   7F   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SUR", "RR   3F   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("SVC", "RR   0A   I1");
        ReservedWordsASM_optableDOS.opcodes.put("SW", "RX   6F   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("SWR", "RR   2F   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("SXR", "RR   37   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("TCH", "S    9F00 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("TIO", "S    9D00 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("TITLE", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("TM", "SI   91   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("TR", "SS   DC   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("TRT", "SS   DD   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("TS", "S    9300 D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("UNPK", "SS   F3   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("USING", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("WRD", "SI   84   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("WXTRN", "HLASM");
        ReservedWordsASM_optableDOS.opcodes.put("X", "RX   57   R1,D2(X2,B2)");
        ReservedWordsASM_optableDOS.opcodes.put("XC", "SS   D7   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableDOS.opcodes.put("XI", "SI   97   D1(B1),I2");
        ReservedWordsASM_optableDOS.opcodes.put("XR", "RR   17   R1,R2");
        ReservedWordsASM_optableDOS.opcodes.put("ZAP", "SS   F8   D1(L1,B1),D2(L2,B2)");
    }
}
