// 
// Decompiled by Procyon v0.5.36
// 

package com.ibm.dmh.scan.classify.reservedWords;

import java.util.TreeMap;
import java.util.Map;

public class ReservedWordsASM_optable370
{
    private static final String copyright = "Licensed Material - Property of IBM\n5724-V27\nCopyright IBM Corp. 2017\nThe source code for this program is not published or otherwise\ndivested of its trade secrets, irrespective of what has been\ndeposited with the U.S. Copyright Office.";
    private static final Map<String, String> opcodes;
    
    public static boolean containsKey(final String token) {
        return ReservedWordsASM_optable370.opcodes.containsKey(token);
    }
    
    public static String get(final String key) {
        return ReservedWordsASM_optable370.opcodes.get(key);
    }
    
    static {
        (opcodes = new TreeMap<String, String>()).put("A", "RX   5A   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("ACONTROL", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ACTR", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AD", "RX   6A   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("ADATA", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ADR", "RR   2A   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("AE", "RX   7A   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("AEJECT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AER", "RR   3A   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("AGO", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AGOB", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AH", "RX   4A   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("AIF", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AIFB", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AINSERT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AL", "RX   5E   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("ALIAS", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ALR", "RR   1E   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("AMODE", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ANOP", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AP", "SS   FA   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optable370.opcodes.put("AR", "RR   1A   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("AREAD", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ASPACE", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("AU", "RX   7E   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("AUR", "RR   3E   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("AW", "RX   6E   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("AWR", "RR   2E   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("AXR", "RR   36   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("B", "RX   47F. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BAL", "RX   45   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BALR", "RR   05   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("BAS", "RX   4D   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BASR", "RR   0D   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("BC", "RX   47   M1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BCR", "RR   07   M1,R2");
        ReservedWordsASM_optable370.opcodes.put("BCT", "RX   46   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BCTR", "RR   06   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("BE", "RX   478. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BER", "RR   078. R2");
        ReservedWordsASM_optable370.opcodes.put("BH", "RX   472. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BHR", "RR   072. R2");
        ReservedWordsASM_optable370.opcodes.put("BL", "RX   474. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BLR", "RR   074. R2");
        ReservedWordsASM_optable370.opcodes.put("BM", "RX   474. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BMR", "RR   074. R2");
        ReservedWordsASM_optable370.opcodes.put("BNE", "RX   477. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BNER", "RR   077. R2");
        ReservedWordsASM_optable370.opcodes.put("BNH", "RX   47D. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BNHR", "RR   07D. R2");
        ReservedWordsASM_optable370.opcodes.put("BNL", "RX   47B. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BNLR", "RR   07B. R2");
        ReservedWordsASM_optable370.opcodes.put("BNM", "RX   47B. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BNMR", "RR   07B. R2");
        ReservedWordsASM_optable370.opcodes.put("BNO", "RX   47E. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BNOR", "RR   07E. R2");
        ReservedWordsASM_optable370.opcodes.put("BNP", "RX   47D. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BNPR", "RR   07D. R2");
        ReservedWordsASM_optable370.opcodes.put("BNZ", "RX   477. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BNZR", "RR   077. R2");
        ReservedWordsASM_optable370.opcodes.put("BO", "RX   471. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BOR", "RR   071. R2");
        ReservedWordsASM_optable370.opcodes.put("BP", "RX   472. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BPR", "RR   072. R2");
        ReservedWordsASM_optable370.opcodes.put("BR", "RR   07F. R2");
        ReservedWordsASM_optable370.opcodes.put("BXH", "RS   86   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("BXLE", "RS   87   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("BZ", "RX   478. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("BZR", "RR   078. R2");
        ReservedWordsASM_optable370.opcodes.put("C", "RX   59   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("CATTR", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("CCW", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("CCW0", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("CCW1", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("CD", "RX   69   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("CDR", "RR   29   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("CDS", "RS   BB   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("CE", "RX   79   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("CEJECT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("CER", "RR   39   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("CH", "RX   49   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("CL", "RX   55   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("CLC", "SS   D5   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("CLCL", "RR   0F   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("CLI", "SI   95   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("CLM", "RS   BD   R1,M3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("CLR", "RR   15   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("CLRCH", "S    9F01 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("CLRIO", "S    9D01 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("CNOP", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("COM", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("CONCS", "S    B200 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("COPY", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("CP", "SS   F9   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optable370.opcodes.put("CR", "RR   19   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("CS", "RS   BA   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("CSECT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("CVB", "RX   4F   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("CVD", "RX   4E   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("CXD", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("D", "RX   5D   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("DC", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("DD", "RX   6D   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("DDR", "RR   2D   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("DE", "RX   7D   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("DER", "RR   3D   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("DISCS", "S    B201 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("DP", "SS   FD   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optable370.opcodes.put("DR", "RR   1D   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("DROP", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("DS", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("DSECT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("DXD", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ED", "SS   DE   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("EDMK", "SS   DF   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("EJECT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("END", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ENTRY", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("EPAR", "RRE  B226 R1");
        ReservedWordsASM_optable370.opcodes.put("EQU", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ESAR", "RRE  B227 R1");
        ReservedWordsASM_optable370.opcodes.put("EX", "RX   44   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("EXITCTL", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("EXTRN", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("GBLA", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("GBLB", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("GBLC", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("HDR", "RR   24   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("HDV", "S    9E01 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("HER", "RR   34   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("HIO", "S    9E00 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("IAC", "RRE  B224 R1");
        ReservedWordsASM_optable370.opcodes.put("IC", "RX   43   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("ICM", "RS   BF   R1,M3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("ICTL", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("IPK", "S    B20B");
        ReservedWordsASM_optable370.opcodes.put("IPTE", "RRE  B221 R1,R2");
        ReservedWordsASM_optable370.opcodes.put("ISEQ", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("ISK", "RR   09   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("ISKE", "RRE  B229 R1,R2");
        ReservedWordsASM_optable370.opcodes.put("IVSK", "RRE  B223 R1,R2");
        ReservedWordsASM_optable370.opcodes.put("L", "RX   58   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("LA", "RX   41   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("LASP", "SSE  E500 D1(B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("LCDR", "RR   23   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LCER", "RR   33   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LCLA", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("LCLB", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("LCLC", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("LCR", "RR   13   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LCTL", "RS   B7   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("LD", "RX   68   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("LDR", "RR   28   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LE", "RX   78   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("LER", "RR   38   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LH", "RX   48   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("LM", "RS   98   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("LNDR", "RR   21   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LNER", "RR   31   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LNR", "RR   11   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LOCTR", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("LPDR", "RR   20   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LPER", "RR   30   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LPR", "RR   10   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LPSW", "S    8200 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("LR", "RR   18   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LRA", "RX   B1   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("LRDR", "RR   25   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LRER", "RR   35   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LTDR", "RR   22   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LTER", "RR   32   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("LTORG", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("LTR", "RR   12   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("M", "RX   5C   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("MACRO", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("MC", "SI   AF   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("MD", "RX   6C   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("MDE", "RX   7C   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("MDER", "RR   3C   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("MDR", "RR   2C   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("ME", "RX   7C   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("MEND", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("MER", "RR   3C   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("MEXIT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("MH", "RX   4C   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("MHELP", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("MNOTE", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("MP", "SS   FC   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optable370.opcodes.put("MR", "RR   1C   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("MVC", "SS   D2   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("MVCIN", "SS   E8   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("MVCK", "SS   D9   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optable370.opcodes.put("MVCL", "RR   0E   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("MVCP", "SS   DA   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optable370.opcodes.put("MVCS", "SS   DB   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optable370.opcodes.put("MVI", "SI   92   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("MVN", "SS   D1   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("MVO", "SS   F1   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optable370.opcodes.put("MVZ", "SS   D3   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("MXD", "RX   67   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("MXDR", "RR   27   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("MXR", "RR   26   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("N", "RX   54   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("NC", "SS   D4   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("NI", "SI   94   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("NOP", "RX   470. D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("NOPR", "RR   070. R2");
        ReservedWordsASM_optable370.opcodes.put("NR", "RR   14   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("O", "RX   56   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("OC", "SS   D6   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("OI", "SI   96   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("OPSYN", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("OR", "RR   16   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("ORG", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("PACK", "SS   F2   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optable370.opcodes.put("PC", "S    B218 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("POP", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("PRINT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("PT", "RRE  B228 R1,R2");
        ReservedWordsASM_optable370.opcodes.put("PTLB", "S    B20D");
        ReservedWordsASM_optable370.opcodes.put("PUNCH", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("PUSH", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("RDD", "SI   85   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("REPRO", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("RIO", "S    9C02 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("RMODE", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("RRB", "S    B213 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("RRBE", "RRE  B22A R1,R2");
        ReservedWordsASM_optable370.opcodes.put("RSECT", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("S", "RX   5B   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("SAC", "S    B219 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SCK", "S    B204 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SCKC", "S    B206 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SD", "RX   6B   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("SDR", "RR   2B   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("SE", "RX   7B   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("SER", "RR   3B   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("SETA", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("SETAF", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("SETB", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("SETC", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("SETCF", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("SH", "RX   4B   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("SIGP", "RS   AE   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SIO", "S    9C00 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SIOF", "S    9C01 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SL", "RX   5F   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("SLA", "RS   8B   R1,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SLDA", "RS   8F   R1,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SLDL", "RS   8D   R1,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SLL", "RS   89   R1,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SLR", "RR   1F   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("SP", "SS   FB   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optable370.opcodes.put("SPACE", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("SPKA", "S    B20A D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SPM", "RR   04   R1");
        ReservedWordsASM_optable370.opcodes.put("SPT", "S    B208 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SPX", "S    B210 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SR", "RR   1B   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("SRA", "RS   8A   R1,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SRDA", "RS   8E   R1,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SRDL", "RS   8C   R1,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SRL", "RS   88   R1,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SRP", "SS   F0   D1(L1,B1),D2(B2),I3");
        ReservedWordsASM_optable370.opcodes.put("SSAR", "RRE  B225 R1");
        ReservedWordsASM_optable370.opcodes.put("SSK", "RR   08   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("SSKE", "RRE  B22B R1,R2");
        ReservedWordsASM_optable370.opcodes.put("SSM", "S    8000 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("ST", "RX   50   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("STAP", "S    B212 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("START", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("STC", "RX   42   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("STCK", "S    B205 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("STCKC", "S    B207 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("STCM", "RS   BE   R1,M3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("STCTL", "RS   B6   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("STD", "RX   60   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("STE", "RX   70   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("STH", "RX   40   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("STIDC", "S    B203 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("STIDP", "S    B202 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("STM", "RS   90   R1,R3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("STNSM", "SI   AC   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("STOSM", "SI   AD   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("STPT", "S    B209 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("STPX", "S    B211 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("SU", "RX   7F   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("SUR", "RR   3F   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("SVC", "RR   0A   I1");
        ReservedWordsASM_optable370.opcodes.put("SW", "RX   6F   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("SWR", "RR   2F   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("SXR", "RR   37   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("TB", "RRE  B22C R1,R2");
        ReservedWordsASM_optable370.opcodes.put("TCH", "S    9F00 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("TIO", "S    9D00 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("TITLE", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("TM", "SI   91   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("TPROT", "SSE  E501 D1(B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("TR", "SS   DC   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("TRT", "SS   DD   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("TS", "S    9300 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("UNPK", "SS   F3   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optable370.opcodes.put("USING", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("VA", "VST  A420 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VACD", "VST  A417 VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VACDR", "VV   A517 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VACE", "VST  A407 VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VACER", "VV   A507 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VACRS", "S    A6CB D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VACSV", "S    A6CA D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VAD", "VST  A410 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VADQ", "QV   A590 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VADR", "VV   A510 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VADS", "QST  A490 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VAE", "VST  A400 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VAEQ", "QV   A580 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VAER", "VV   A500 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VAES", "QST  A480 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VAQ", "QV   A5A0 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VAR", "VV   A520 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VAS", "QST  A4A0 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VC", "VST  A428 M1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VCD", "VST  A418 M1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VCDQ", "QV   A598 M1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VCDR", "VV   A518 M1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VCDS", "QST  A498 M1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VCE", "VST  A408 M1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VCEQ", "QV   A588 M1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VCER", "VV   A508 M1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VCES", "QST  A488 M1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VCOVM", "RRE  A643 R1");
        ReservedWordsASM_optable370.opcodes.put("VCQ", "QV   A5A8 M1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VCR", "VV   A528 M1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VCS", "QST  A4A8 M1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VCVM", "RRE  A641");
        ReservedWordsASM_optable370.opcodes.put("VCZVM", "RRE  A642 R1");
        ReservedWordsASM_optable370.opcodes.put("VDD", "VST  A413 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VDDQ", "QV   A593 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VDDR", "VV   A513 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VDDS", "QST  A493 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VDE", "VST  A403 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VDEQ", "QV   A583 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VDER", "VV   A503 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VDES", "QST  A483 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VL", "VST  A409 VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLBIX", "RSEv E428 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VLCDR", "VV   A552 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLCER", "VV   A542 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLCR", "VV   A562 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLCVM", "VS   A681 RS2");
        ReservedWordsASM_optable370.opcodes.put("VLD", "VST  A419 VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLDQ", "QV   A599 VR1,QR2");
        ReservedWordsASM_optable370.opcodes.put("VLDR", "VV   A519 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLE", "VST  A409 VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLEL", "VR   A628 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VLELD", "VR   A618 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VLELE", "VR   A608 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VLEQ", "QV   A589 VR1,QR2");
        ReservedWordsASM_optable370.opcodes.put("VLER", "VV   A509 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLH", "VST  A429 VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLI", "RSEv E400 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VLID", "RSEv E410 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VLIE", "RSEv E400 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VLINT", "VST  A42A VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLM", "VST  A40A VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLMD", "VST  A41A VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLMDQ", "QV   A59A VR1,QR2");
        ReservedWordsASM_optable370.opcodes.put("VLMDR", "VV   A51A VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLME", "VST  A40A VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLMEQ", "QV   A58A VR1,QR2");
        ReservedWordsASM_optable370.opcodes.put("VLMER", "VV   A50A VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLMQ", "QV   A5AA VR1,QR2");
        ReservedWordsASM_optable370.opcodes.put("VLMR", "VV   A50A VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLNDR", "VV   A551 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLNER", "VV   A541 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLNR", "VV   A561 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLPDR", "VV   A550 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLPER", "VV   A540 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLPR", "VV   A560 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLQ", "QV   A5A9 VR1,QR2");
        ReservedWordsASM_optable370.opcodes.put("VLR", "VV   A509 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VLVCA", "S    A6C4 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VLVCU", "RRE  A645 R1");
        ReservedWordsASM_optable370.opcodes.put("VLVM", "VS   A680 RS2");
        ReservedWordsASM_optable370.opcodes.put("VLVXA", "S    A6C7 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VLY", "VST  A40B VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLYD", "VST  A41B VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLYE", "VST  A40B VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VLZDR", "VV   A51B VR1");
        ReservedWordsASM_optable370.opcodes.put("VLZER", "VV   A50B VR1");
        ReservedWordsASM_optable370.opcodes.put("VLZR", "VV   A50B VR1");
        ReservedWordsASM_optable370.opcodes.put("VM", "VST  A422 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMAD", "VST  A414 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMADQ", "QV   A594 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMADS", "QST  A494 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMAE", "VST  A404 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMAEQ", "QV   A584 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMAES", "QST  A484 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMCD", "VST  A416 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMCDR", "VV   A516 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMCE", "VST  A406 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMCER", "VV   A506 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMD", "VST  A412 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMDQ", "QV   A592 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMDR", "VV   A512 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMDS", "QST  A492 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VME", "VST  A402 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMEQ", "QV   A582 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMER", "VV   A502 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMES", "QST  A482 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMNSD", "VR   A611 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VMNSE", "VR   A601 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VMQ", "QV   A5A2 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMR", "VV   A522 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMRRS", "S    A6C3 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VMRSV", "S    A6C1 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VMS", "QST  A4A2 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMSD", "VST  A415 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMSDQ", "QV   A595 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMSDS", "QST  A495 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMSE", "VST  A405 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMSEQ", "QV   A585 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VMSES", "QST  A485 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VMXAD", "VR   A612 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VMXAE", "VR   A602 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VMXSD", "VR   A610 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VMXSE", "VR   A600 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VN", "VST  A424 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VNQ", "QV   A5A4 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VNR", "VV   A524 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VNS", "QST  A4A4 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VNVM", "VS   A684 RS2");
        ReservedWordsASM_optable370.opcodes.put("VO", "VST  A425 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VOQ", "QV   A5A5 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VOR", "VV   A525 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VOS", "QST  A4A5 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VOVM", "VS   A685 RS2");
        ReservedWordsASM_optable370.opcodes.put("VRCL", "S    A6C5 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VRRS", "RRE  A648 R1");
        ReservedWordsASM_optable370.opcodes.put("VRSV", "RRE  A64A R1");
        ReservedWordsASM_optable370.opcodes.put("VRSVC", "RRE  A649 R1");
        ReservedWordsASM_optable370.opcodes.put("VS", "VST  A421 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSD", "VST  A411 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSDQ", "QV   A591 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VSDR", "VV   A511 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VSDS", "QST  A491 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSE", "VST  A401 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSEQ", "QV   A581 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VSER", "VV   A501 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VSES", "QST  A481 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSLL", "RSEv E425 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VSPSD", "VR   A61A VR1,QR2");
        ReservedWordsASM_optable370.opcodes.put("VSQ", "QV   A5A1 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VSQD", "VST  A453 VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSQDR", "VV   A553 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VSQE", "VST  A443 VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSQER", "VV   A543 VR1,VR2");
        ReservedWordsASM_optable370.opcodes.put("VSR", "VV   A521 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VSRL", "RSEv E424 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VSRRS", "S    A6C2 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VSRSV", "S    A6C0 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VSS", "QST  A4A1 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VST", "VST  A40D VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTD", "VST  A41D VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTE", "VST  A40D VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTH", "VST  A42D VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTI", "RSEv E401 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VSTID", "RSEv E411 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VSTIE", "RSEv E401 VR1,VR3,D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VSTK", "VST  A40F VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTKD", "VST  A41F VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTKE", "VST  A40F VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTM", "VST  A40E VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTMD", "VST  A41E VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTME", "VST  A40E VR1,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VSTVM", "VS   A682 RS2");
        ReservedWordsASM_optable370.opcodes.put("VSTVP", "S    A6C8 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VSVMM", "S    A6C6 D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("VTAD", "VST  A454 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VTAE", "VST  A444 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VTSD", "VST  A455 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VTSE", "VST  A445 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VTVM", "RRE  A640");
        ReservedWordsASM_optable370.opcodes.put("VX", "VST  A426 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VXEL", "VR   A629 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VXELD", "VR   A619 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VXELE", "VR   A609 VR1,QR3,R2");
        ReservedWordsASM_optable370.opcodes.put("VXQ", "QV   A5A6 VR1,QR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VXR", "VV   A526 VR1,VR3,VR2");
        ReservedWordsASM_optable370.opcodes.put("VXS", "QST  A4A6 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optable370.opcodes.put("VXVC", "RRE  A644 R1");
        ReservedWordsASM_optable370.opcodes.put("VXVM", "VS   A686 RS2");
        ReservedWordsASM_optable370.opcodes.put("VXVMM", "RRE  A646 R1");
        ReservedWordsASM_optable370.opcodes.put("VZPSD", "VR   A61B VR1");
        ReservedWordsASM_optable370.opcodes.put("WRD", "SI   84   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("WXTRN", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("X", "RX   57   R1,D2(X2,B2)");
        ReservedWordsASM_optable370.opcodes.put("XATTR", "HLASM");
        ReservedWordsASM_optable370.opcodes.put("XC", "SS   D7   D1(L,B1),D2(B2)");
        ReservedWordsASM_optable370.opcodes.put("XI", "SI   97   D1(B1),I2");
        ReservedWordsASM_optable370.opcodes.put("XR", "RR   17   R1,R2");
        ReservedWordsASM_optable370.opcodes.put("ZAP", "SS   F8   D1(L1,B1),D2(L2,B2)");
    }
}
