// 
// Decompiled by Procyon v0.5.36
// 

package com.ibm.dmh.scan.classify.reservedWords;

import java.util.TreeMap;
import java.util.Map;

public class ReservedWordsASM_optableESA
{
    private static final String copyright = "Licensed Material - Property of IBM\n5724-V27\nCopyright IBM Corp. 2017\nThe source code for this program is not published or otherwise\ndivested of its trade secrets, irrespective of what has been\ndeposited with the U.S. Copyright Office.";
    private static final Map<String, String> opcodes;
    
    public static boolean containsKey(final String token) {
        return ReservedWordsASM_optableESA.opcodes.containsKey(token);
    }
    
    public static String get(final String key) {
        return ReservedWordsASM_optableESA.opcodes.get(key);
    }
    
    static {
        (opcodes = new TreeMap<String, String>()).put("A", "RX   5A   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("ACONTROL", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("ACTR", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AD", "RX   6A   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("ADATA", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("ADB", "RXE  ED1A R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("ADBR", "RRE  B31A R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("ADR", "RR   2A   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("AE", "RX   7A   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("AEB", "RXE  ED0A R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("AEBR", "RRE  B30A R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("AEJECT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AER", "RR   3A   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("AGO", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AGOB", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AH", "RX   4A   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("AHI", "RI   A7.A R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("AIF", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AIFB", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AINSERT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AL", "RX   5E   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("ALC", "RXE  E398 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("ALCR", "RRE  B998 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("ALIAS", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("ALR", "RR   1E   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("AMODE", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("ANOP", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AP", "SS   FA   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("AR", "RR   1A   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("AREAD", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("ASPACE", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("AU", "RX   7E   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("AUR", "RR   3E   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("AW", "RX   6E   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("AWR", "RR   2E   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("AXBR", "RRE  B34A R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("AXR", "RR   36   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("B", "RX   47F. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BAKR", "RRE  B240 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BAL", "RX   45   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BALR", "RR   05   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BAS", "RX   4D   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BASR", "RR   0D   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BASSM", "RR   0C   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BC", "RX   47   M1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BCR", "RR   07   M1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BCT", "RX   46   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BCTR", "RR   06   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BE", "RX   478. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BER", "RR   078. R2");
        ReservedWordsASM_optableESA.opcodes.put("BH", "RX   472. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BHR", "RR   072. R2");
        ReservedWordsASM_optableESA.opcodes.put("BL", "RX   474. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BLR", "RR   074. R2");
        ReservedWordsASM_optableESA.opcodes.put("BM", "RX   474. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BMR", "RR   074. R2");
        ReservedWordsASM_optableESA.opcodes.put("BNE", "RX   477. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BNER", "RR   077. R2");
        ReservedWordsASM_optableESA.opcodes.put("BNH", "RX   47D. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BNHR", "RR   07D. R2");
        ReservedWordsASM_optableESA.opcodes.put("BNL", "RX   47B. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BNLR", "RR   07B. R2");
        ReservedWordsASM_optableESA.opcodes.put("BNM", "RX   47B. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BNMR", "RR   07B. R2");
        ReservedWordsASM_optableESA.opcodes.put("BNO", "RX   47E. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BNOR", "RR   07E. R2");
        ReservedWordsASM_optableESA.opcodes.put("BNP", "RX   47D. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BNPR", "RR   07D. R2");
        ReservedWordsASM_optableESA.opcodes.put("BNZ", "RX   477. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BNZR", "RR   077. R2");
        ReservedWordsASM_optableESA.opcodes.put("BO", "RX   471. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BOR", "RR   071. R2");
        ReservedWordsASM_optableESA.opcodes.put("BP", "RX   472. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BPR", "RR   072. R2");
        ReservedWordsASM_optableESA.opcodes.put("BR", "RR   07F. R2");
        ReservedWordsASM_optableESA.opcodes.put("BRAS", "RI   A7.5 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("BRASL", "RIL  C0.5 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("BRC", "RI   A7.4 M1,I2");
        ReservedWordsASM_optableESA.opcodes.put("BRCL", "RIL  C0.4 M1,I2");
        ReservedWordsASM_optableESA.opcodes.put("BRCT", "RI   A7.6 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("BRE", "RI   A784 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRH", "RI   A724 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRL", "RI   A744 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRM", "RI   A744 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRNE", "RI   A774 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRNH", "RI   A7D4 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRNL", "RI   A7B4 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRNM", "RI   A7B4 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRNO", "RI   A7E4 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRNP", "RI   A7D4 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRNZ", "RI   A774 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRO", "RI   A714 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRP", "RI   A724 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRU", "RI   A7F4 I2");
        ReservedWordsASM_optableESA.opcodes.put("BRXH", "RSI  84   R1,R3,I2");
        ReservedWordsASM_optableESA.opcodes.put("BRXLE", "RSI  85   R1,R3,I2");
        ReservedWordsASM_optableESA.opcodes.put("BRZ", "RI   A784 I2");
        ReservedWordsASM_optableESA.opcodes.put("BSA", "RRE  B25A R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BSG", "RRE  B258 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BSM", "RR   0B   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("BXH", "RS   86   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("BXLE", "RS   87   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("BZ", "RX   478. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("BZR", "RR   078. R2");
        ReservedWordsASM_optableESA.opcodes.put("C", "RX   59   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CATTR", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("CCW", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("CCW0", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("CCW1", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("CD", "RX   69   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CDB", "RXE  ED19 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CDBR", "RRE  B319 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CDFBR", "RRE  B395 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CDFR", "RRE  B3B5 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CDR", "RR   29   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CDS", "RS   BB   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("CE", "RX   79   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CEB", "RXE  ED09 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CEBR", "RRE  B309 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CEFBR", "RRE  B394 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CEFR", "RRE  B3B4 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CEJECT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("CER", "RR   39   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CFC", "S    B21A D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("CFDBR", "RRF  B399 R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("CFDR", "RRF  B3B9 R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("CFEBR", "RRF  B398 R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("CFER", "RRF  B3B8 R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("CFXBR", "RRF  B39A R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("CFXR", "RRF  B3BA R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("CH", "RX   49   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CHI", "RI   A7.E R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("CKSM", "RRE  B241 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CL", "RX   55   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CLC", "SS   D5   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("CLCL", "RR   0F   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CLCLE", "RS   A9   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("CLI", "SI   95   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("CLM", "RS   BD   R1,M3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("CLR", "RR   15   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CLST", "RRE  B25D R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CMPSC", "RRE  B263 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CNOP", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("COM", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("COPY", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("CP", "SS   F9   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CPYA", "RRE  B24D R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CR", "RR   19   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CS", "RS   BA   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("CSCH", "S    B230");
        ReservedWordsASM_optableESA.opcodes.put("CSECT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("CUSE", "RRE  B257 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CUTFU", "RRE  B2A7 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CUUTF", "RRE  B2A6 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CVB", "RX   4F   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CVD", "RX   4E   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("CXBR", "RRE  B349 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CXD", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("CXFBR", "RRE  B396 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CXFR", "RRE  B3B6 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("CXR", "RRE  B369 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("D", "RX   5D   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("DC", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("DD", "RX   6D   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("DDB", "RXE  ED1D R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("DDBR", "RRE  B31D R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("DDR", "RR   2D   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("DE", "RX   7D   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("DEB", "RXE  ED0D R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("DEBR", "RRE  B30D R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("DER", "RR   3D   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("DIDBR", "RRF  B35B R1,R3,R2,M4");
        ReservedWordsASM_optableESA.opcodes.put("DIEBR", "RRF  B353 R1,R3,R2,M4");
        ReservedWordsASM_optableESA.opcodes.put("DL", "RXE  E397 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("DLR", "RRE  B997 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("DP", "SS   FD   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("DR", "RR   1D   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("DROP", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("DS", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("DSECT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("DXBR", "RRE  B34D R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("DXD", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("DXR", "RRE  B22D R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("EAR", "RRE  B24F R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("ED", "SS   DE   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("EDMK", "SS   DF   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("EFPC", "RRE  B38C R1");
        ReservedWordsASM_optableESA.opcodes.put("EJECT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("END", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("ENTRY", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("EPAR", "RRE  B226 R1");
        ReservedWordsASM_optableESA.opcodes.put("EPSW", "RRE  B98D R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("EQU", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("EREG", "RRE  B249 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("ESAR", "RRE  B227 R1");
        ReservedWordsASM_optableESA.opcodes.put("ESTA", "RRE  B24A R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("EX", "RX   44   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("EXITCTL", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("EXTRN", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("FIDBR", "RRF  B35F R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("FIDR", "RRE  B37F R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("FIEBR", "RRF  B357 R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("FIER", "RRE  B377 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("FIXBR", "RRF  B347 R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("FIXR", "RRE  B367 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("GBLA", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("GBLB", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("GBLC", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("HDR", "RR   24   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("HER", "RR   34   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("HSCH", "S    B231");
        ReservedWordsASM_optableESA.opcodes.put("IAC", "RRE  B224 R1");
        ReservedWordsASM_optableESA.opcodes.put("IC", "RX   43   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("ICM", "RS   BF   R1,M3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("ICTL", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("IPK", "S    B20B");
        ReservedWordsASM_optableESA.opcodes.put("IPM", "RRE  B222 R1");
        ReservedWordsASM_optableESA.opcodes.put("IPTE", "RRE  B221 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("ISEQ", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("ISKE", "RRE  B229 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("IVSK", "RRE  B223 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("J", "RI   A7F4 I2");
        ReservedWordsASM_optableESA.opcodes.put("JAS", "RI   A7.5 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("JASL", "RIL  C0.5 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("JC", "RI   A7.4 M1,I2");
        ReservedWordsASM_optableESA.opcodes.put("JCT", "RI   A7.6 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("JE", "RI   A784 I2");
        ReservedWordsASM_optableESA.opcodes.put("JH", "RI   A724 I2");
        ReservedWordsASM_optableESA.opcodes.put("JL", "RI   A744 I2");
        ReservedWordsASM_optableESA.opcodes.put("JLC", "RIL  C0.4 M1,I2");
        ReservedWordsASM_optableESA.opcodes.put("JLNOP", "RIL  C004 I2");
        ReservedWordsASM_optableESA.opcodes.put("JM", "RI   A744 I2");
        ReservedWordsASM_optableESA.opcodes.put("JNE", "RI   A774 I2");
        ReservedWordsASM_optableESA.opcodes.put("JNH", "RI   A7D4 I2");
        ReservedWordsASM_optableESA.opcodes.put("JNL", "RI   A7B4 I2");
        ReservedWordsASM_optableESA.opcodes.put("JNM", "RI   A7B4 I2");
        ReservedWordsASM_optableESA.opcodes.put("JNO", "RI   A7E4 I2");
        ReservedWordsASM_optableESA.opcodes.put("JNOP", "RI   A704 I2");
        ReservedWordsASM_optableESA.opcodes.put("JNP", "RI   A7D4 I2");
        ReservedWordsASM_optableESA.opcodes.put("JNZ", "RI   A774 I2");
        ReservedWordsASM_optableESA.opcodes.put("JO", "RI   A714 I2");
        ReservedWordsASM_optableESA.opcodes.put("JP", "RI   A724 I2");
        ReservedWordsASM_optableESA.opcodes.put("JXH", "RSI  84   R1,R3,I2");
        ReservedWordsASM_optableESA.opcodes.put("JXLE", "RSI  85   R1,R3,I2");
        ReservedWordsASM_optableESA.opcodes.put("JZ", "RI   A784 I2");
        ReservedWordsASM_optableESA.opcodes.put("KDB", "RXE  ED18 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("KDBR", "RRE  B318 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("KEB", "RXE  ED08 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("KEBR", "RRE  B308 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("KXBR", "RRE  B348 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("L", "RX   58   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LA", "RX   41   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LAE", "RX   51   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LAM", "RS   9A   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("LARL", "RIL  C0.0 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("LASP", "SSE  E500 D1(B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("LCDBR", "RRE  B313 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LCDR", "RR   23   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LCEBR", "RRE  B303 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LCER", "RR   33   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LCLA", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("LCLB", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("LCLC", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("LCR", "RR   13   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LCTL", "RS   B7   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("LCXBR", "RRE  B343 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LCXR", "RRE  B363 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LD", "RX   68   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LDE", "RXE  ED24 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LDEB", "RXE  ED04 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LDEBR", "RRE  B304 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LDER", "RRE  B324 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LDR", "RR   28   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LDXBR", "RRE  B345 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LDXR", "RR   25   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LE", "RX   78   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LEDBR", "RRE  B344 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LEDR", "RR   35   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LER", "RR   38   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LEXBR", "RRE  B346 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LEXR", "RRE  B366 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LFPC", "S    B29D D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("LH", "RX   48   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LHI", "RI   A7.8 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("LM", "RS   98   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("LNDBR", "RRE  B311 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LNDR", "RR   21   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LNEBR", "RRE  B301 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LNER", "RR   31   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LNR", "RR   11   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LNXBR", "RRE  B341 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LNXR", "RRE  B361 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LOCTR", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("LPDBR", "RRE  B310 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LPDR", "RR   20   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LPEBR", "RRE  B300 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LPER", "RR   30   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LPR", "RR   10   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LPSW", "S    8200 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("LPXBR", "RRE  B340 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LPXR", "RRE  B360 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LR", "RR   18   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LRA", "RX   B1   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LRDR", "RR   25   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LRER", "RR   35   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LRV", "RXE  E31E R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LRVH", "RXE  E31F R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LRVR", "RRE  B91F R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LTDBR", "RRE  B312 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LTDR", "RR   22   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LTEBR", "RRE  B302 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LTER", "RR   32   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LTORG", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("LTR", "RR   12   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LTXBR", "RRE  B342 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LTXR", "RRE  B362 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LURA", "RRE  B24B R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LXD", "RXE  ED25 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LXDB", "RXE  ED05 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LXDBR", "RRE  B305 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LXDR", "RRE  B325 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LXE", "RXE  ED26 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LXEB", "RXE  ED06 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("LXEBR", "RRE  B306 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LXER", "RRE  B326 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LXR", "RRE  B365 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("LZDR", "RRE  B375 R1");
        ReservedWordsASM_optableESA.opcodes.put("LZER", "RRE  B374 R1");
        ReservedWordsASM_optableESA.opcodes.put("LZXR", "RRE  B376 R1");
        ReservedWordsASM_optableESA.opcodes.put("M", "RX   5C   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MACRO", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("MADB", "RXF  ED1E R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MADBR", "RRF  B31E R1,R3,R2");
        ReservedWordsASM_optableESA.opcodes.put("MAEB", "RXF  ED0E R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MAEBR", "RRF  B30E R1,R3,R2");
        ReservedWordsASM_optableESA.opcodes.put("MC", "SI   AF   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("MD", "RX   6C   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MDB", "RXE  ED1C R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MDBR", "RRE  B31C R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MDE", "RX   7C   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MDEB", "RXE  ED0C R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MDEBR", "RRE  B30C R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MDER", "RR   3C   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MDR", "RR   2C   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("ME", "RX   7C   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MEE", "RXE  ED37 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MEEB", "RXE  ED17 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MEEBR", "RRE  B317 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MEER", "RRE  B337 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MEND", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("MER", "RR   3C   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MEXIT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("MH", "RX   4C   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MHELP", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("MHI", "RI   A7.C R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("ML", "RXE  E396 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MLR", "RRE  B996 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MNOTE", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("MP", "SS   FC   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MR", "RR   1C   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MS", "RX   71   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MSCH", "S    B232 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("MSDB", "RXF  ED1F R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MSDBR", "RRF  B31F R1,R3,R2");
        ReservedWordsASM_optableESA.opcodes.put("MSEB", "RXF  ED0F R1,R3,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MSEBR", "RRF  B30F R1,R3,R2");
        ReservedWordsASM_optableESA.opcodes.put("MSR", "RRE  B252 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MSTA", "RRE  B247 R1");
        ReservedWordsASM_optableESA.opcodes.put("MVC", "SS   D2   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("MVCDK", "SSE  E50F D1(B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("MVCIN", "SS   E8   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("MVCK", "SS   D9   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optableESA.opcodes.put("MVCL", "RR   0E   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MVCLE", "RS   A8   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("MVCP", "SS   DA   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optableESA.opcodes.put("MVCS", "SS   DB   D1(R1,B1),D2(B2),R3");
        ReservedWordsASM_optableESA.opcodes.put("MVCSK", "SSE  E50E D1(B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("MVI", "SI   92   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("MVN", "SS   D1   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("MVO", "SS   F1   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MVPG", "RRE  B254 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MVST", "RRE  B255 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MVZ", "SS   D3   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("MXBR", "RRE  B34C R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MXD", "RX   67   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MXDB", "RXE  ED07 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("MXDBR", "RRE  B307 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MXDR", "RR   27   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("MXR", "RR   26   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("N", "RX   54   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("NC", "SS   D4   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("NI", "SI   94   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("NOP", "RX   470. D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("NOPR", "RR   070. R2");
        ReservedWordsASM_optableESA.opcodes.put("NR", "RR   14   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("O", "RX   56   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("OC", "SS   D6   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("OI", "SI   96   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("OPSYN", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("OR", "RR   16   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("ORG", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("PACK", "SS   F2   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("PALB", "RRE  B248");
        ReservedWordsASM_optableESA.opcodes.put("PC", "S    B218 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("PLO", "SS   EE   R1,D2(B2),R3,D4(B4)");
        ReservedWordsASM_optableESA.opcodes.put("POP", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("PR", "E    0101");
        ReservedWordsASM_optableESA.opcodes.put("PRINT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("PT", "RRE  B228 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("PTLB", "S    B20D");
        ReservedWordsASM_optableESA.opcodes.put("PUNCH", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("PUSH", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("RCHP", "S    B23B");
        ReservedWordsASM_optableESA.opcodes.put("REPRO", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("RLL", "RSE  EB1D R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("RMODE", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("RP", "S    B277 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("RRBE", "RRE  B22A R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("RSCH", "S    B238");
        ReservedWordsASM_optableESA.opcodes.put("RSECT", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("S", "RX   5B   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SAC", "S    B219 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SACF", "S    B279 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SAL", "S    B237");
        ReservedWordsASM_optableESA.opcodes.put("SAM24", "E    010C");
        ReservedWordsASM_optableESA.opcodes.put("SAM31", "E    010D");
        ReservedWordsASM_optableESA.opcodes.put("SAR", "RRE  B24E R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SCHM", "S    B23C");
        ReservedWordsASM_optableESA.opcodes.put("SCK", "S    B204 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SCKC", "S    B206 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SCKPF", "E    0107");
        ReservedWordsASM_optableESA.opcodes.put("SD", "RX   6B   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SDB", "RXE  ED1B R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SDBR", "RRE  B31B R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SDR", "RR   2B   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SE", "RX   7B   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SEB", "RXE  ED0B R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SEBR", "RRE  B30B R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SER", "RR   3B   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SETA", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("SETAF", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("SETB", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("SETC", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("SETCF", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("SFPC", "RRE  B384 R1");
        ReservedWordsASM_optableESA.opcodes.put("SH", "RX   4B   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SIE", "S    B214 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SIGP", "RS   AE   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SL", "RX   5F   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SLA", "RS   8B   R1,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SLB", "RXE  E399 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SLBR", "RRE  B999 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SLDA", "RS   8F   R1,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SLDL", "RS   8D   R1,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SLL", "RS   89   R1,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SLR", "RR   1F   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SP", "SS   FB   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SPACE", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("SPKA", "S    B20A D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SPM", "RR   04   R1");
        ReservedWordsASM_optableESA.opcodes.put("SPT", "S    B208 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SPX", "S    B210 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SQD", "RXE  ED35 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SQDB", "RXE  ED15 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SQDBR", "RRE  B315 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SQDR", "RRE  B244 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SQE", "RXE  ED34 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SQEB", "RXE  ED14 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SQEBR", "RRE  B314 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SQER", "RRE  B245 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SQXBR", "RRE  B316 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SQXR", "RRE  B336 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SR", "RR   1B   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SRA", "RS   8A   R1,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SRDA", "RS   8E   R1,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SRDL", "RS   8C   R1,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SRL", "RS   88   R1,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SRNM", "S    B299 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SRP", "SS   F0   D1(L1,B1),D2(B2),I3");
        ReservedWordsASM_optableESA.opcodes.put("SRST", "RRE  B25E R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SSAR", "RRE  B225 R1");
        ReservedWordsASM_optableESA.opcodes.put("SSCH", "S    B233 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("SSKE", "RRE  B22B R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SSM", "S    8000 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("ST", "RX   50   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("STAM", "RS   9B   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STAP", "S    B212 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("START", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("STC", "RX   42   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("STCK", "S    B205 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STCKC", "S    B207 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STCKE", "S    B278 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STCM", "RS   BE   R1,M3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STCPS", "S    B23A D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STCRW", "S    B239 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STCTL", "RS   B6   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STD", "RX   60   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("STE", "RX   70   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("STFL", "S    B2B1 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STFPC", "S    B29C D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STH", "RX   40   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("STIDP", "S    B202 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STM", "RS   90   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STNSM", "SI   AC   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("STOSM", "SI   AD   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("STPT", "S    B209 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STPX", "S    B211 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STRV", "RXE  E33E R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("STRVH", "RXE  E33F R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("STSCH", "S    B234 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STSI", "S    B27D D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("STURA", "RRE  B246 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SU", "RX   7F   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SUR", "RR   3F   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SVC", "RR   0A   I1");
        ReservedWordsASM_optableESA.opcodes.put("SW", "RX   6F   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("SWR", "RR   2F   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SXBR", "RRE  B34B R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("SXR", "RR   37   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("TAM", "E    010B");
        ReservedWordsASM_optableESA.opcodes.put("TAR", "RRE  B24C R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("TB", "RRE  B22C R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("TBDR", "RRF  B351 R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("TBEDR", "RRF  B350 R1,M3,R2");
        ReservedWordsASM_optableESA.opcodes.put("TCDB", "RXE  ED11 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("TCEB", "RXE  ED10 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("TCXB", "RXE  ED12 R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("THDER", "RRE  B358 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("THDR", "RRE  B359 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("TITLE", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("TM", "SI   91   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("TMH", "RI   A7.0 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("TML", "RI   A7.1 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("TMLH", "RI   A7.0 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("TMLL", "RI   A7.1 R1,I2");
        ReservedWordsASM_optableESA.opcodes.put("TPI", "S    B236 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("TPROT", "SSE  E501 D1(B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("TR", "SS   DC   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("TRACE", "RS   99   R1,R3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("TRAP2", "E    01FF");
        ReservedWordsASM_optableESA.opcodes.put("TRAP4", "S    B2FF D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("TRE", "RRE  B2A5 R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("TRT", "SS   DD   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("TS", "S    9300 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("TSCH", "S    B235 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("UNPK", "SS   F3   D1(L1,B1),D2(L2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("UPT", "E    0102");
        ReservedWordsASM_optableESA.opcodes.put("USING", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("VA", "VST  A420 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VACD", "VST  A417 VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VACDR", "VV   A517 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VACE", "VST  A407 VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VACER", "VV   A507 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VACRS", "S    A6CB D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VACSV", "S    A6CA D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VAD", "VST  A410 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VADQ", "QV   A590 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VADR", "VV   A510 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VADS", "QST  A490 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VAE", "VST  A400 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VAEQ", "QV   A580 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VAER", "VV   A500 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VAES", "QST  A480 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VAQ", "QV   A5A0 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VAR", "VV   A520 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VAS", "QST  A4A0 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VC", "VST  A428 M1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VCD", "VST  A418 M1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VCDQ", "QV   A598 M1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VCDR", "VV   A518 M1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VCDS", "QST  A498 M1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VCE", "VST  A408 M1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VCEQ", "QV   A588 M1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VCER", "VV   A508 M1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VCES", "QST  A488 M1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VCOVM", "RRE  A643 R1");
        ReservedWordsASM_optableESA.opcodes.put("VCQ", "QV   A5A8 M1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VCR", "VV   A528 M1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VCS", "QST  A4A8 M1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VCVM", "RRE  A641");
        ReservedWordsASM_optableESA.opcodes.put("VCZVM", "RRE  A642 R1");
        ReservedWordsASM_optableESA.opcodes.put("VDD", "VST  A413 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VDDQ", "QV   A593 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VDDR", "VV   A513 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VDDS", "QST  A493 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VDE", "VST  A403 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VDEQ", "QV   A583 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VDER", "VV   A503 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VDES", "QST  A483 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VL", "VST  A409 VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLBIX", "RSEv E428 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VLCDR", "VV   A552 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLCER", "VV   A542 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLCR", "VV   A562 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLCVM", "VS   A681 RS2");
        ReservedWordsASM_optableESA.opcodes.put("VLD", "VST  A419 VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLDQ", "QV   A599 VR1,QR2");
        ReservedWordsASM_optableESA.opcodes.put("VLDR", "VV   A519 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLE", "VST  A409 VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLEL", "VR   A628 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VLELD", "VR   A618 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VLELE", "VR   A608 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VLEQ", "QV   A589 VR1,QR2");
        ReservedWordsASM_optableESA.opcodes.put("VLER", "VV   A509 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLH", "VST  A429 VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLI", "RSEv E400 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VLID", "RSEv E410 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VLIE", "RSEv E400 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VLINT", "VST  A42A VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLM", "VST  A40A VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLMD", "VST  A41A VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLMDQ", "QV   A59A VR1,QR2");
        ReservedWordsASM_optableESA.opcodes.put("VLMDR", "VV   A51A VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLME", "VST  A40A VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLMEQ", "QV   A58A VR1,QR2");
        ReservedWordsASM_optableESA.opcodes.put("VLMER", "VV   A50A VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLMQ", "QV   A5AA VR1,QR2");
        ReservedWordsASM_optableESA.opcodes.put("VLMR", "VV   A50A VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLNDR", "VV   A551 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLNER", "VV   A541 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLNR", "VV   A561 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLPDR", "VV   A550 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLPER", "VV   A540 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLPR", "VV   A560 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLQ", "QV   A5A9 VR1,QR2");
        ReservedWordsASM_optableESA.opcodes.put("VLR", "VV   A509 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VLVCA", "S    A6C4 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VLVCU", "RRE  A645 R1");
        ReservedWordsASM_optableESA.opcodes.put("VLVM", "VS   A680 RS2");
        ReservedWordsASM_optableESA.opcodes.put("VLVXA", "S    A6C7 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VLY", "VST  A40B VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLYD", "VST  A41B VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLYE", "VST  A40B VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VLZDR", "VV   A51B VR1");
        ReservedWordsASM_optableESA.opcodes.put("VLZER", "VV   A50B VR1");
        ReservedWordsASM_optableESA.opcodes.put("VLZR", "VV   A50B VR1");
        ReservedWordsASM_optableESA.opcodes.put("VM", "VST  A422 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMAD", "VST  A414 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMADQ", "QV   A594 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMADS", "QST  A494 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMAE", "VST  A404 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMAEQ", "QV   A584 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMAES", "QST  A484 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMCD", "VST  A416 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMCDR", "VV   A516 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMCE", "VST  A406 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMCER", "VV   A506 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMD", "VST  A412 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMDQ", "QV   A592 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMDR", "VV   A512 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMDS", "QST  A492 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VME", "VST  A402 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMEQ", "QV   A582 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMER", "VV   A502 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMES", "QST  A482 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMNSD", "VR   A611 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VMNSE", "VR   A601 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VMQ", "QV   A5A2 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMR", "VV   A522 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMRRS", "S    A6C3 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VMRSV", "S    A6C1 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VMS", "QST  A4A2 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMSD", "VST  A415 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMSDQ", "QV   A595 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMSDS", "QST  A495 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMSE", "VST  A405 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMSEQ", "QV   A585 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VMSES", "QST  A485 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VMXAD", "VR   A612 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VMXAE", "VR   A602 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VMXSD", "VR   A610 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VMXSE", "VR   A600 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VN", "VST  A424 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VNQ", "QV   A5A4 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VNR", "VV   A524 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VNS", "QST  A4A4 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VNVM", "VS   A684 RS2");
        ReservedWordsASM_optableESA.opcodes.put("VO", "VST  A425 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VOQ", "QV   A5A5 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VOR", "VV   A525 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VOS", "QST  A4A5 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VOVM", "VS   A685 RS2");
        ReservedWordsASM_optableESA.opcodes.put("VRCL", "S    A6C5 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VRRS", "RRE  A648 R1");
        ReservedWordsASM_optableESA.opcodes.put("VRSV", "RRE  A64A R1");
        ReservedWordsASM_optableESA.opcodes.put("VRSVC", "RRE  A649 R1");
        ReservedWordsASM_optableESA.opcodes.put("VS", "VST  A421 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSD", "VST  A411 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSDQ", "QV   A591 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VSDR", "VV   A511 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VSDS", "QST  A491 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSE", "VST  A401 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSEQ", "QV   A581 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VSER", "VV   A501 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VSES", "QST  A481 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSLL", "RSEv E425 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VSPSD", "VR   A61A VR1,QR2");
        ReservedWordsASM_optableESA.opcodes.put("VSQ", "QV   A5A1 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VSQD", "VST  A453 VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSQDR", "VV   A553 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VSQE", "VST  A443 VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSQER", "VV   A543 VR1,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VSR", "VV   A521 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VSRL", "RSEv E424 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VSRRS", "S    A6C2 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VSRSV", "S    A6C0 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VSS", "QST  A4A1 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VST", "VST  A40D VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTD", "VST  A41D VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTE", "VST  A40D VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTH", "VST  A42D VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTI", "RSEv E401 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTID", "RSEv E411 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTIE", "RSEv E401 VR1,VR3,D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTK", "VST  A40F VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTKD", "VST  A41F VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTKE", "VST  A40F VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTM", "VST  A40E VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTMD", "VST  A41E VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTME", "VST  A40E VR1,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VSTVM", "VS   A682 RS2");
        ReservedWordsASM_optableESA.opcodes.put("VSTVP", "S    A6C8 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VSVMM", "S    A6C6 D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("VTAD", "VST  A454 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VTAE", "VST  A444 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VTSD", "VST  A455 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VTSE", "VST  A445 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VTVM", "RRE  A640");
        ReservedWordsASM_optableESA.opcodes.put("VX", "VST  A426 VR1,VR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VXEL", "VR   A629 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VXELD", "VR   A619 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VXELE", "VR   A609 VR1,QR3,R2");
        ReservedWordsASM_optableESA.opcodes.put("VXQ", "QV   A5A6 VR1,QR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VXR", "VV   A526 VR1,VR3,VR2");
        ReservedWordsASM_optableESA.opcodes.put("VXS", "QST  A4A6 VR1,QR3,RS2(RT2)");
        ReservedWordsASM_optableESA.opcodes.put("VXVC", "RRE  A644 R1");
        ReservedWordsASM_optableESA.opcodes.put("VXVM", "VS   A686 RS2");
        ReservedWordsASM_optableESA.opcodes.put("VXVMM", "RRE  A646 R1");
        ReservedWordsASM_optableESA.opcodes.put("VZPSD", "VR   A61B VR1");
        ReservedWordsASM_optableESA.opcodes.put("WXTRN", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("X", "RX   57   R1,D2(X2,B2)");
        ReservedWordsASM_optableESA.opcodes.put("XATTR", "HLASM");
        ReservedWordsASM_optableESA.opcodes.put("XC", "SS   D7   D1(L,B1),D2(B2)");
        ReservedWordsASM_optableESA.opcodes.put("XI", "SI   97   D1(B1),I2");
        ReservedWordsASM_optableESA.opcodes.put("XR", "RR   17   R1,R2");
        ReservedWordsASM_optableESA.opcodes.put("XSCH", "S    B276");
        ReservedWordsASM_optableESA.opcodes.put("ZAP", "SS   F8   D1(L1,B1),D2(L2,B2)");
    }
}
